// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace tic.data.Model
{
    public partial class PlayerGame
    {
        public PlayerGame()
        {
            Square = new HashSet<Square>();
        }

        public int PlayerGameId { get; set; }
        public int? GameId { get; set; }
        public int PlayerId { get; set; }
        public byte[] RowVersion { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Guid RowGuid { get; set; }
        public string Symbol { get; set; }

        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
        public virtual ICollection<Square> Square { get; set; }
    }
}