// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace tic.data.Model
{
    public partial class Square
    {
        public int SquareId { get; set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }
        public int GameId { get; set; }
        public int? PlayerGameId { get; set; }
        public byte[] RowVersion { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Guid RowGuid { get; set; }

        public virtual PlayerGame PlayerGame { get; set; }
    }
}