// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using tic.data.Model;

namespace tic.data.DBContext
{
    public class PlayerGameConfiguration : IEntityTypeConfiguration<PlayerGame>
    {
        public void Configure(EntityTypeBuilder<PlayerGame> entity)
        {
            entity.ToTable("Player_Game");

            entity.Property(e => e.PlayerGameId).HasColumnName("PlayerGameID");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.GameId).HasColumnName("GameID");

            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.Property(e => e.PlayerId).HasColumnName("PlayerID");

            entity.Property(e => e.RowGuid).HasColumnName("RowGUID");

            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.Property(e => e.Symbol)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.Game)
                .WithMany(p => p.PlayerGame)
                .HasForeignKey(d => d.GameId)
                .HasConstraintName("FK_Player_Game_Game");

            entity.HasOne(d => d.Player)
                .WithMany(p => p.PlayerGame)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Player_Game_Player");
        }
    }
}
