// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using tic.data.Model;

namespace tic.data.DBContext
{
    public class SquareConfiguration : IEntityTypeConfiguration<Square>
    {
        public void Configure(EntityTypeBuilder<Square> entity)
        {
            entity.Property(e => e.SquareId).HasColumnName("SquareID");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.GameId).HasColumnName("GameID");

            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.Property(e => e.PlayerGameId).HasColumnName("PlayerGameID");

            entity.Property(e => e.RowGuid).HasColumnName("RowGUID");

            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.PlayerGame)
                .WithMany(p => p.Square)
                .HasForeignKey(d => d.PlayerGameId)
                .HasConstraintName("FK_Square_Player_Game");
        }
    }
}
